### ISSUE TITLE
Pro 2.7 Installer fails

### ISSUE THREAD

**Issue by spgriffin** [Esri/deep-learning-frameworks#13]
I have Pro 2.7 installed but the deep learning library installer for 2.7 fails (Error 2343. Specified path is empty).  I had no issue with 2.6 when I was using that version.

I can install manually, but the installer is ideal because it places libraries into the base arcgispro-py3 environment.

**Comment by sandeepgadhwal** [comment]
> I have Pro 2.7 installed but the deep learning library installer for 2.7 fails (Error 2343. Specified path is empty). I had no issue with 2.6 when I was using that version.
> 
> I can install manually, but the installer is ideal because it places libraries into the base arcgispro-py3 environment.

Is there a difference between your ArcGIS Pro 2.7 and the previous installation of ArcGIS Pro 2.6 ?

Is it installed system wide or just for your user ?

**Comment by spgriffin** [comment]
Other than the version being different, the installation of the software
remained the same.  There software is installed system wide.  I'm not that
concerned.  I manually installed the deep learning frameworks myself and
will use this environment.

**Comment by scdub** [comment]
@spgriffin It sounds like you were able to address the issue locally -- if it reoccurs, let us know and we can dig in further. It may be related to antivirus or other security software running in your environment, but for now will close this. Thanks!
