### ISSUE TITLE
Failed to train Deep learning model

### ISSUE THREAD

**Issue by ArcGisProUser** [Esri/deep-learning-frameworks#15]
Hi,

Thank you so much for building dependencies installer. Its makes the life easier. 

I need your help in training deep learning model. Kindly share some video tutorial for building object detection model using deep learning in ArcGIS-Pro. 

I have tried to build model using png chips in KITTI, PASCALVOC, classified tiles, label tiles........ however, system is not accepting any kind of data.  :( 

please Esri help me....... i am trying since last week. its almost ten days now.

looking forward for your support

cheers

**Comment by ArcGisProUser** [comment]
after exporting the data, two folders are created one is image and another is label. Label folder is empty....


Any fix?

**Comment by scdub** [comment]
@ArcGisProUser were you able to address this problem on your own? There are a number of example workflows like the [palm tree health](https://learn.arcgis.com/en/projects/use-deep-learning-to-assess-palm-tree-health/) exercise.
