### ISSUE TITLE
Update for RTX 30 Series GPUs (CUDA 11)

### ISSUE THREAD

**Issue by oSilentCartographer** [Esri/deep-learning-frameworks#17]
When can we expect updated libraries for RTX 30 series GPUs? They have been out for over 7 months now. 
I have an RTX 3090 but it cannot run any deep learning tasks through ArcGIS Pro. My understanding is that these new GPUs require CUDA 11 support. It looks like these libraries need updated versions of PyTorch and TensorFlow as well.

**Comment by knoopum** [comment]
I'm looking forward to these updates as well. Thanks!

**Comment by Hulseyj** [comment]
New RTX 3060. I am experiencing an error when I use "Detect Objects Using Deep Learning" in ArcGIS Pro with new RTX 3060. The model used is usa_building_footprints.dlpk. I am using ArcGIS Pro 2.7.3. I have no issues running the model with my GTX 1650 Super GPU, same computer, same settings. 

I have a post on this issue in the ESRI Community forums here: [https://community.esri.com/t5/arcgis-pro-questions/detect-objects-using-deep-learning-error-with-new-rtx-3060/m-p/1050015#M40037](url) 

Still trying to find a resolution.

**Comment by oSilentCartographer** [comment]
> 
> 
> New RTX 3060. I am experiencing an error when I use "Detect Objects Using Deep Learning" in ArcGIS Pro with new RTX 3060. The model used is usa_building_footprints.dlpk. I am using ArcGIS Pro 2.7.3. I have no issues running the model with my GTX 1650 Super GPU, same computer, same settings.
> 
> I have a post on this issue in the ESRI Community forums here: [https://community.esri.com/t5/arcgis-pro-questions/detect-objects-using-deep-learning-error-with-new-rtx-3060/m-p/1050015#M40037](url)
> 
> Still trying to find a resolution.

**Comment by oSilentCartographer** [comment]
Sorry I clicked close accidentally!

I meant to reply to Hulseyj:

I have communicated with ESRI support multiple times about this issue and have yet to get any details about future plans to upgrade the libraries for the latest GPUs. They did admit that this is caused by lack of CUDA 11 support.

**Comment by njpamperin** [comment]
Using an NVIDIA RTX 3080 laptop (and CUDA 11.3) and having issues with deep learning tools as well (device side CUDA assert errors). Just adding my name to the list of those having issues with the new 30xx series cards. Hoping for a solution soon.

**Comment by Samsa95** [comment]
I'm using a RTX 3060 laptop version and got problems with the tools as well (nan values when using the GPU), probably because of the above mentioned lack of actual libraries. Hope for a fast update to use this tools.

**Comment by njpamperin** [comment]
> 
> 
> I'm using a RTX 3060 laptop version and got problems with the tools as well (nan values when using the GPU), probably because of the above mentioned lack of actual libraries. Hope for a fast update to use this tools.

Yes, depending on the model I am trying to train on the RTX 3080 (laptop) I also get nan for training and validation loss values when trying to use GPU processing. This mainly happens with SSD whereas trying to train MaskRCNN produces the device side CUDA assert error.

**Comment by MattBC90** [comment]
Oh my god, guys!  I have been trying to figure out why the heck I couldn't get any of this working as it should for over a month now.  I have a 3080 and I've encountered pretty much all of the same errors mentioned.

I got around some of the ArcGIS notebook issues for model training by doing it inside of an external Jupyter browser, but just as soon as I was making progress, I got stonewalled when I kept getting "nan" values while trying to train the thing.  I thought I was going crazy!  

I am actually exploring various means to do GIS Deep Learning so I guess I have little choice but to look at how to do these steps through open source code, which ArcGIS seems to use anyway.  More of a hassle but it's either this way or no project.

**Comment by PetrieSwart1970** [comment]
Hi All. Hving the same problem with ArcGIS PRO 2.7 and RTX 3060. CUDA version installed is 11.2.

**Comment by njpamperin** [comment]
> 
> 
> Oh my god, guys! I have been trying to figure out why the heck I couldn't get any of this working as it should for over a month now. I have a 3080 and I've encountered pretty much all of the same errors mentioned.
> 
> I got around some of the ArcGIS notebook issues for model training by doing it inside of an external Jupyter browser, but just as soon as I was making progress, I got stonewalled when I kept getting "nan" values while trying to train the thing. I thought I was going crazy!
> 
> I am actually exploring various means to do GIS Deep Learning so I guess I have little choice but to look at how to do these steps through open source code, which ArcGIS seems to use anyway. More of a hassle but it's either this way or no project.

Make sure you check the Esri community post referenced by Hulseyj above. It sounds like Esri is working on a solution.

**Comment by MattBC90** [comment]
> Make sure you check the Esri community post referenced by Hulseyj above. It sounds like Esri is working on a solution.

That link doesn't lead anywhere for me.  Either way, I doubt anything will be working by the time I have to complete my project.  Maybe they just assumed everybody with RTX 3000 series GPUs were only using them for mining, which is only partially true.

**Comment by scdub** [comment]
Thank you for providing details on your workflows and your interest in using the deep learning tools on Ampere based GPUs. As you have discovered, Ampere cards are not consistently supported by CUDA 10 based solutions. The deep learning collection includes eight separate GPU backed packages, which are all compiled against the CUDA Toolkit 10.1 release. Unfortunately, some of these dependencies have not been fully updated to support Ampere currently, and CUDA 10.1 does not natively support the binary formats Ampere provides, only CUDA 11.1+ does as you can see in this table:

<img width="331" alt="image" src="https://user-images.githubusercontent.com/46331011/118010866-68e20b00-b31d-11eb-9997-3db9506e78d5.png">

When you run GPU based code, there are two primary execution paths: a targeted cubin binary which is optimized for the specific architecture, and is what you generally want to use. The fallback is PTX, which will JIT compile a kernel from an older GPU target onto the current GPU. However, this translation in places can be problematic and introduces errors as has been documented above, though it will work in many cases with simpler CUDA code (the last column provides details on what binary and PTX versions are included in our bundled PyTorch build).

## Future Pro plans

Our plan for Pro 2.8 is to continue distributing a collection of installers and package set targeted at CUDA Tookilt 10.1, and works for GPUs of the last Kepler generation (3.7 with Tesla K80), Maxwell, Pascal, Turing, and Volta GPUs. This collection of packages has gone through extensive validation, and covers the GPUs for a broad base of our users, and has upstream support from the packages we are redistributing or building. **For Ampere users**, we have been working toward a _technology preview_ that will be available by UC 2021, which will have some known limitations but allow key `arcgis.learn`, DL based geoprocessing tools and core libraries to function, using CUDA 11 and cubins for the CC 8.6 platform. There won't be an installer for this technology preview, but it will be available as a conda installable metapackage, and once we post this, we will be sure to respond to this issue as well.

For the release of Pro which will arrive Q4 2021, we will support Ampere out of the box as a target for the deep learning installers, and will have a solution based on CUDA Toolkit 11.

**Comment by SrikantaESV** [comment]
I'm also facing the same problem, any lead on this would be highly appreciated- 

Traceback (most recent call last):
  File "c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Image Analyst Tools.tbx\TrainDeepLearningModel.tool\tool.script.execute.py", line 297, in <module>
    execute()
  File "c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Image Analyst Tools.tbx\TrainDeepLearningModel.tool\tool.script.execute.py", line 271, in execute
    callbacks=[ProgressCallback(training_model_object, model_type, max_epochs, out_folder)]
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\learn\models\_arcgis_model.py", line 798, in fit
    self.learn.fit_one_cycle(epochs, lr, callbacks=callbacks, **kwargs)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\fastai\train.py", line 23, in fit_one_cycle
    learn.fit(cyc_len, max_lr, wd=wd, callbacks=callbacks)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\fastai\basic_train.py", line 200, in fit
    fit(epochs, self, metrics=self.metrics, callbacks=self.callbacks+callbacks)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\fastai\basic_train.py", line 101, in fit
    loss = loss_batch(learn.model, xb, yb, learn.loss_func, learn.opt, cb_handler)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\fastai\basic_train.py", line 26, in loss_batch
    out = model(*xb)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\torchvision\models\detection\generalized_rcnn.py", line 70, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\torchvision\models\detection\rpn.py", line 472, in forward
    boxes, scores = self.filter_proposals(proposals, objectness, images.image_sizes, num_anchors_per_level)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\torchvision\models\detection\rpn.py", line 392, in filter_proposals
    keep = box_ops.remove_small_boxes(boxes, self.min_size)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\torchvision\ops\boxes.py", line 95, in remove_small_boxes
    keep = keep.nonzero().squeeze(1)
RuntimeError: copy_if failed to synchronize: cudaErrorAssert: device-side assert triggered

**Comment by oSilentCartographer** [comment]
Do we have any more info about the "technology preview" that was slated to be ready by UC 2021?

**Comment by Hornbydd** [comment]
I was advised to add to this list to emphasise that my attempts to do pixel classification using deep learning have failed possibly due to the fact I have an RTX 3070 card. My attempts and failure has been documented here:

https://community.esri.com/t5/arcgis-pro-questions/help-with-deep-learning-and-pixel-classification/m-p/1081251#M43557

I do hope the appropriate libraries are updated soon!

**Comment by geoli91** [comment]
I'm looking forward to these updates. Also, I'd like to know if we can upgrade the versionf of PyTorch and CUDA ourselves via conda or other means? I tried to do that, but conda gave me a bunch of conflict.

**Comment by oSilentCartographer** [comment]
I spent a lot of time trying to figure out if I could manually update PyTorch, TensorFlow, etc., but it all ended in failure. I think I got some things installed by changing the version limits. But there are many internal references/dependencies regarding the versions -- e.g., this thing will only work if PyTorch is version ___. I tried editing those too, but still could not get things working. 

We are still waiting for the technology preview that might help some of us circumvent these issues. It is overdue at this point; hoping they release it soon.

**Comment by pchristensengis** [comment]
conda esri deep-learning-ampere-preview is live on anaconda.org

(https://anaconda.org/Esri/deep-learning-ampere-preview)

**Comment by oSilentCartographer** [comment]
Anyone have luck getting this to work? Or any update on an additional fix?

**Comment by oSilentCartographer** [comment]
Anyone have luck getting this to work? Or any update on an additional fix?

(sorry I accidentally clicked "close" again)

**Comment by oSilentCartographer** [comment]
Anyone have luck getting this to work? Or any update on an additional fix?

(sorry I accidentally clicked "close" again)

**Comment by aamrufl** [comment]
I am also trying to train deep learning network after following the deep-learning-ampere-preview installation instructions on 3070 with no luck.

**Comment by SrikantaESV** [comment]
Is there any update or clue to fix the issue?

**Comment by AbdullahAlfayez** [comment]
We all have been waiting for a fix since March! Any update since you mentioned there will be a solution by November?

**Comment by RossDF** [comment]
Has there been any further development with this?
I was under the impression that it was going to be part of the ArcGIS Pro 1.9 release, however I can't see any mention in patch notes.

**Comment by data4point0** [comment]
> 
> 
> Has there been any further development with this? I was under the impression that it was going to be part of the ArcGIS Pro 2.9 release, however I can't see any mention in patch notes.

I am also interested to see if there has been a 2.9 update in this regard - nothing mentioned in the patch

**Comment by oSilentCartographer** [comment]
I just installed 2.9 and the accompanying deep learning frameworks (follow conda install instructions), which do have updated versions of Pytorch, Tensorflow, etc. 

But something still seems wrong. While my GPU is now being utilized with the Detect Objects tool, each time it ends in "ERROR 160722: The item was not found." Same outcome if I use the CPU too.
I have never encountered this error when using this tool in the past (with older GPUs that I know to work).

**Comment by oSilentCartographer** [comment]
Upon more testing, it appears that having "Non Maximum Suppression" selected is causing the tool to fail. Unchecked and it works, but of course the output has overlapping detections that I do not want. Can anyone think of why this is happening?

**Comment by AbdullahAlfayez** [comment]
> Upon more testing, it appears that having "Non Maximum Suppression" selected is causing the tool to fail. Unchecked and it works, but of course the output has overlapping detections that I do not want. Can anyone think of why this is happening?


Does training a model work with you though? @oSilentCartographer

**Comment by oSilentCartographer** [comment]
> > Upon more testing, it appears that having "Non Maximum Suppression" selected is causing the tool to fail. Unchecked and it works, but of course the output has overlapping detections that I do not want. Can anyone think of why this is happening?
> 
> Does training a model work with you though? @oSilentCartographer

I still have to test model training. But I did find that there is a separate standalone Non Maximum Suppression tool, and I can run it after Detect Objects (with NMS turned off), and that actually works. It's an extra step, but this is major progress! 

In other words, only the NMS within the Detect Objects tool is broken, and it turns out that is more of a convenience than a necessity.

**Comment by Hulseyj** [comment]
I am happy to report that Detect Objects Using Deep Learning is running successfully with my RTX 3060 after performing a clean install of ArcPro 2.9.0 and the 2.9 Deep Learning Libraries. I am seeing a significant improvement in speed as compared to my RTX 1650 Super. I have tested the Building Footprint Extraction deep learning model that is published by ESRI on the Living Atlas. I see better results in terms of speed when I use the default tile size environment settings (I remove the model argument: tile size 512). I have run the model in ArcPro and Jupyter notebook successfully. 

Thanks to all who have worked to solve the issue with using the deep learning tools on the new Ampere cards.

**Comment by scdub** [comment]
I believe the original issue raised here has been addressed with the DL installation for Pro 2.9, and Ampere cards are now part of our internal testing process. If anyone is having issues on Pro 2.9 using Ampere cards, let's move those conversations to new issues as this is now supported and is likely specific to particular tools or models.

**Comment by leijiang1122** [comment]
> Have you ever encountered 002667 error while performing deep learning target detection on arcgispro 3.0 with 3060 graphics card?
