### ISSUE TITLE
ArcGIS Pro 2.8 - Deep Learning with GPU - Fatal authorization error

### ISSUE THREAD

**Issue by tmcginnes** [Esri/deep-learning-frameworks#19]
Wanting to try out some of the new deep learning tools in Pro 2.8. I have a clean install of 2.8, cloned Python environment and the deep learning modules installed by "conda install deep-learning-essentials", which does install the 2.8 version.

I can successfully run the deep learning tools with CPU specified in the environment variables. But when I choose GPU I  get an error box popup: "ArcGIS Pro has experienced a fatal authorization error and must close". Screenshot attached.
![tool_error_messages](https://user-images.githubusercontent.com/84295913/118418038-1d9f7200-b6fa-11eb-9ccc-0f67abf5d75f.jpg)

These tools have the error when using GPU:
Classify Pixels Using Deep Learning
Detect Change Using Deep Learning
Detect Objects Using Deep Learning

These tools work without problems when using GPU:
Train Deep Learning Model
Classify Point Cloud Using Trained Model

All the tools above work without problems when using CPU.

I have ArcGIS Pro 2.8 Advanced and the Image Analyst extension licensed as a named user through ArcGIS Online. The same thing is occurring on two different machines, desktop with 5Gb Quadro P2000 and laptop with 8Gb GeForce RTX 2080. Both machines on Windows 10.

Am I just too quick off the mark trying to do deep learning in Pro 2.8?

**Comment by Landman79** [comment]
I have same issue. Installed deep-lerning-essentials 2.8. Even upgraded google-auth. The  same problem - no inferencing, only training. Error - the same as above. GPU RTX 2070 11 Gb

**Comment by sang4758** [comment]
This issue has been fixed and will be updated in the next Pro 2.8 patch

**Comment by shingike** [comment]
I noticed the same error while running in CPU. Is the solution would eliminate the issue in CPU execution as well? Do you know when we will receive the next Pro 2.8 patch that includes this solution?

**Comment by sang4758** [comment]
Hi @shingike , you will notice the error in CPU if you set the parallel processing factor more than 0. The 2.8.1 patch is scheduled to be out in the next couple of  weeks.

**Comment by shingike** [comment]
Good to know! Definitely keep my eyes on the release and try it out once it's out. Thanks!!

**Comment by tmcginnes** [comment]
The ArcGIS Pro 2.8.1 patch does indeed seem to resolve this issue. Thanks.

**Comment by shingike** [comment]
Same here. It seems to work in my end as well. Thanks!

**Comment by MesquiteGIS** [comment]
where do you get the 2.8.1 patch? Thanks

**Comment by tmcginnes** [comment]
The patch is for ArcGIS Pro itself, not the deep learning framework. You can download the offline installer through the MyEsri website, or update in ArcGIS Pro - go to Settings then About. Should tell you what version you have and I think there is a button to update.
