### ISSUE TITLE
arcgis.learn.classify_objects on local raster?

### ISSUE THREAD

**Issue by shingike** [Esri/deep-learning-frameworks#22]
Does arcgis.learn.classify_objects work on local raster?

There is **prepare_data** and **FeatureClassifier** that work on local folders to generate a model, but once the model is saved, I cannot run arcgis.learn.classify_objects to classify object from the local feature class. Both input raster and input feature need to come from the portal item. 

Do I need to run _arcpy.ia.ClassifyObjectsUsingDeepLearning_ to work with the local image and feature class? I am hoping not to use arcpy and use arcgis.learn to do all the export, training and inference, but it seems like there are no alternatives.

**Comment by scdub** [comment]
@shingike thanks for your question. This repository is primarily focused on the underlying framework build for using and running deep learning workflows. For a question specifically on a method signature for the Python API, could you report this issue [to their public repository?](https://github.com/Esri/arcgis-python-api/issues). If it doesn't support local rasters, that should be documented.
