### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by ej-takase** [Esri/deep-learning-frameworks#26]
Hi
The documentation for Pro 2.8 Manual Installation  is incorrect.
4. Type the following commands to install the deep learning packages. If prompted to proceed, review the information, type y, and press Enter.

Change request
Current : protobuf 3.14.0.1
Change:  protobuf 3.14.0

Best
Hiroshi

**Comment by scdub** [comment]
@ej-takase Thank you for your report! I've edited the PDF and updated it in this repository.
