### ISSUE TITLE
Endless Training loop Arcpro 2.7.4

### ISSUE THREAD

**Issue by ajacquez2** [Esri/deep-learning-frameworks#27]
Hello, 

I have installed Arpro 2.7.4 and I have started training a model, but Arcpro has been stuck in an endless training that was never present in 2.7.3. I have been waiting to train a model and not even a percentage has moved or training has started. Could you provide me with the Arcpro Deep learning Library install for 2.7.4 or is there something else going on. I have previously upgraded to Arcpro 2.8.1, but since then have not been able to train as a model due to countless errors so reverted to 2.7.4 and now things seem to not work.

**Comment by scdub** [comment]
@ajacquez2 were you able to address this issue? I'm not aware of anything specifically with 2.7.4, but if you are still running into problems training the model, we can look into it further.
