### ISSUE TITLE
Arcpro 2.8.1 Deep learning The domain name is invalid

### ISSUE THREAD

**Issue by ajacquez2** [Esri/deep-learning-frameworks#28]
after training my deep learning model I am unable to use my models and have an error code show down below. I have tried multiple fixes uninstalling and installing latest update and now fix. Could I get some support and trying to fix this issue. I am working in arcpro 2.8.1.

error 160676: the domain name is invalid.

**Comment by cleebp** [comment]
After reinstalling with 2.8 and installing the latest update did you use the deep learning setup installers and recreate your deep learning environment?

**Comment by ajacquez2** [comment]
Yes I did. I made sure I uninstall the all libraries and install arcpro 2.8 libraries again and make sure I clone the once again.

**Comment by ajacquez2** [comment]
![Error_Arcpro](https://user-images.githubusercontent.com/25391510/127017283-7d3064c2-d25d-43e7-8ff4-a18a9a32cb02.PNG)

**Comment by ajacquez2** [comment]
I just trained this model and tried running to detect object and same error

**Comment by cleebp** [comment]
Can you use your clone and try to `import tensorflow-gpu` in the Pro python interpreter at the bottom or in a Pro jupyter notebook?

**Comment by ajacquez2** [comment]
![Error_2_Arcpro](https://user-images.githubusercontent.com/25391510/127018175-9d9bbddc-475b-4f20-9cc7-7dd6e7d48a35.PNG)

**Comment by ajacquez2** [comment]
![image](https://user-images.githubusercontent.com/25391510/127018931-8d3a2faa-ff38-4bbd-ab9a-c36882988738.png)

**Comment by cleebp** [comment]
Oh sorry it might be `tensorflow_gpu`.

**Comment by ajacquez2** [comment]
![image](https://user-images.githubusercontent.com/25391510/127019288-ff847d0c-9de2-4e02-9a5e-83ec9bed4d75.png)

**Comment by cleebp** [comment]
Interesting, I might have been mistaken about which tensorflow was available in 2.8.1, could you try to `import torch` instead?

**Comment by ajacquez2** [comment]
![image](https://user-images.githubusercontent.com/25391510/127023100-1bb1de1f-38d0-461a-ac07-a0b88f776a73.png)

**Comment by cleebp** [comment]
Okay thats good at least, it means your Pro can use pytorch which makes the error messages all that weirder, I'll message some folks internally and see if this has popped up before.

**Comment by ajacquez2** [comment]
I was using Arcpro deep learning with no issue until I tried making new models and then things just stopped working.

**Comment by ajacquez2** [comment]
I also uninstalled everything and downloaded what's available in the github page and still same issues.

**Comment by scdub** [comment]
@ajacquez2 were you able to address this issue? Based on the above details, it looks like it may be an issue with the DLPK or the tool, and likely is best we put you in touch from someone from those areas if you haven't been able to get the model to work.

**Comment by scdub** [comment]
@ajacquez2 we haven't heard back from you on this issue, but we can reopen it if you're still trying to figure it out.

**Comment by pooya-rezvan** [comment]
Hello,
I face this error just as I start the tool "detecting object for DL".
I noticed that another user had the same problem, but the ticket was closed.
I am using ArcGIS Pro 2.7 and all the required modules are already installed and my GPU is working well.

Thank you so much,
Pooya
