### ISSUE TITLE
ERROR 002667

### ISSUE THREAD

**Issue by goriliukasbuxton** [Esri/deep-learning-frameworks#29]
trying to run object detection from existing model.
installed environment using instructions from this repo.
for some reason it is not using the active 'deeplearning' environment either.

ERROR 002667  Unable to initialize python raster function with scalar arguments. [C:\Users\******\AppData\Local\Temp\ArcGISProTemp4184\ParcelExtraction_USA.dlpk\ArcGISImageClassifier.py]
Traceback (most recent call last):
  File "C:\Users\******\Documents\ArcGIS\Packages\resources\models\raster\ee7a5cf6ea4242f7a33014c6d16096ce\ArcGISImageClassifier.py", line 165, in initialize
    self.child_image_classifier.initialize(model, model_as_file)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\learn\models\_inferencing\_model_extension_inferencing.py", line 364, in initialize
    raise Exception('PyTorch is not installed. Install it using conda install -c pytorch pytorch torchvision')
Exception: PyTorch is not installed. Install it using conda install -c pytorch pytorch torchvision

**Comment by scdub** [comment]
@goriliukasbuxton were you able to fix this issue? If not, can you open a Python Command Prompt session, and provide the output of `conda list` for the default arcgispro-py3 environment?

**Comment by scdub** [comment]
@goriliukasbuxton In the absence of additional information, going to close this issue for now. If you have installed the DL extension and don't see PyTorch, please provide the output from `conda list` and we can take a look.
