### ISSUE TITLE
Deep Learning Libraries for ArcGIS pro has not detected ArcGIS pro 2.8

### ISSUE THREAD

**Issue by Afaf-Git** [Esri/deep-learning-frameworks#30]
Hi, I have ArcGIS Pro 2,8 running in my machine. 

I downloaded and unzipped ProDeepLearning libraries but the installation failed, the error message was"Deep Learning Libraries for ArcGIS pro has not detected ArcGIS pro 2.8".
I followed the suggested manual installation but this failed too. for some reason the error msgs that came up when trying to clone py3 using the python command prompt is "CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/esri/win-64/arcgispro-2.7-0.tar.bz2>"

Any idea why this is happening? I'm still learning the deeplearning, so I could have done something wrong in the process.
any help is much appreciated.

Thanks,
Afaf

**Comment by geoli91** [comment]
Maybe you can see https://links.esri.com/deep-learning-framework-install . This provides a simple installation procedure for a deep learning environment. Running it will create a conda environment called arcgispro-dl, which will contain various modules that will be used.

**Comment by geoli91** [comment]
> Hi, I have ArcGIS Pro 2,8 running in my machine.
> 
> I downloaded and unzipped ProDeepLearning libraries but the installation failed, the error message was"Deep Learning Libraries for ArcGIS pro has not detected ArcGIS pro 2.8".
> I followed the suggested manual installation but this failed too. for some reason the error msgs that came up when trying to clone py3 using the python command prompt is "CondaHTTPError: HTTP 000 CONNECTION FAILED for url https://conda.anaconda.org/esri/win-64/arcgispro-2.7-0.tar.bz2"
> 
> Any idea why this is happening? I'm still learning the deeplearning, so I could have done something wrong in the process.
> any help is much appreciated.
> 
> Thanks,
> Afaf

Maybe you can see https://links.esri.com/deep-learning-framework-install . This provides a simple installation procedure for a deep learning environment. Running it will create a conda environment called arcgispro-dl, which will contain various modules that will be used.

**Comment by Afaf-Git** [comment]
Thanks heaps @cleebp, I updated Arcpro version and it worked fine.

**Comment by scdub** [comment]
Glad to hear you were able to address this with reinstallation. Closing this issue, but feel free to create a new one if you run into further problems.
