### ISSUE TITLE
Error 032659 Train Deep Learning Model ArcPRO 2.8.2

### ISSUE THREAD

**Issue by tyhayward** [Esri/deep-learning-frameworks#31]
Hi, 

I cannot train a deep learning model within arcgispro using the 'train deep learning model' geoprocess. I get the following when i select a folder containing the chips + labels (generated from the export deep learning training data geoprocess):

ERROR 032659 updateParameters Error: Traceback (most recent call last):
  File "c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Image Analyst Tools.tbx\TrainDeepLearningModel.tool\tool.script.validate.py", line 427, in <module>
  File "c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Image Analyst Tools.tbx\TrainDeepLearningModel.tool\tool.script.validate.py", line 158, in updateParameters
    import arcgis.learn
  File "C:\Users\Thayward\AppData\Local\ESRI\conda\envs\deeplearning\Lib\site-packages\arcgis\__init__.py", line 4, in <module>
    from . import (features, geoanalytics, geocoding, geometry)
  File "C:\Users\Thayward\AppData\Local\ESRI\conda\envs\deeplearning\Lib\site-packages\arcgis\features\__init__.py", line 28, in <module>
    from . import enrich_data
  File "C:\Users\Thayward\AppData\Local\ESRI\conda\envs\deeplearning\Lib\site-packages\arcgis\features\enrich_data.py", line 10, in <module>
    import arcgis.network as network
  File "C:\Users\Thayward\AppData\Local\ESRI\conda\envs\deeplearning\Lib\site-packages\arcgis\network\__init__.py", line 7, in <module>
    from ._layer import NetworkLayer, NetworkDataset, ClosestFacilityLayer, ServiceAreaLayer, RouteLayer, NAJob, ODCostMatrixLayer
  File "C:\Users\Thayward\AppData\Local\ESRI\conda\envs\deeplearning\Lib\site-packages\arcgis\network\_layer.py", line 8, in <module>
    from arcgis.mapping import MapImageLayer
  File "C:\Users\Thayward\AppData\Local\ESRI\conda\envs\deeplearning\Lib\site-packages\arcgis\mapping\__init__.py", line 8, in <module>
    from ._types import WebMap, WebScene, MapImageLayer, MapImageLayerManager, VectorTileLayer, OfflineMapAreaManager, PackagingJob
  File "C:\Users\Thayward\AppData\Local\ESRI\conda\envs\deeplearning\Lib\site-packages\arcgis\mapping\_types.py", line 25, in <module>
    from arcgis.widgets._mapview._traitlets_extension import ObservableDict
  File "C:\Users\Thayward\AppData\Local\ESRI\conda\envs\deeplearning\Lib\site-packages\arcgis\widgets\__init__.py", line 2, in <module>
    from arcgis.widgets._mapview import MapView
  File "C:\Users\Thayward\AppData\Local\ESRI\conda\envs\deeplearning\Lib\site-packages\arcgis\widgets\_mapview\__init__.py", line 1, in <module>
    from arcgis.widgets._mapview._mapview import MapView
  File "C:\Users\Thayward\AppData\Local\ESRI\conda\envs\deeplearning\Lib\site-packages\arcgis\widgets\_mapview\_mapview.py", line 37, in <module>
    import pandas as pd
  File "C:\Users\Thayward\AppData\Local\ESRI\conda\envs\deeplearning\Lib\site-packages\pandas\__init__.py", line 22, in <module>
    from pandas.compat import (
  File "C:\Users\Thayward\AppData\Local\ESRI\conda\envs\deeplearning\Lib\site-packages\pandas\compat\__init__.py", line 23, in <module>
    from pandas.compat.pyarrow import (
  File "C:\Users\Thayward\AppData\Local\ESRI\conda\envs\deeplearning\Lib\site-packages\pandas\compat\pyarrow.py", line 9, in <module>
    _palv = Version(_pa_version)
  File "C:\Users\Thayward\AppData\Local\ESRI\conda\envs\deeplearning\Lib\site-packages\pandas\util\version\__init__.py", line 339, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object

![image](https://user-images.githubusercontent.com/54058249/133059950-eeb556a3-29c8-4a47-bde6-32edf80265fb.png)
the input images are an 8bit 3band raster. 

others on the esri site have discovered this is a bug relating to 2.8 but no-one from ESRI has replied so I am posting it here to try to get it fixed. 

https://community.esri.com/t5/arcgis-pro-questions/error-032659-train-deep-learning-model/td-p/1067655
https://community.esri.com/t5/arcgis-pro-questions/train-deep-learning-model-error-032659/td-p/1009299
my env details:
# packages in environment at C:\Users\Thayward\AppData\Local\ESRI\conda\envs\deeplearning:
#
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu
absl-py                   0.13.0           py37haa95532_0
appdirs                   1.4.4              pyhd3eb1b0_0
arcgis                    1.8.5                 py37_1783    esri
arcgispro                 2.8                           0    esri
arcpy                     2.8             py37_arcgispro_29734  [arcgispro]  esri
arrow-cpp                 1.0.1                         3    esri
ase                       3.19.1                   py37_0    esri
asn1crypto                1.4.0                      py_0
astor                     0.8.1            py37haa95532_0
atomicwrites              1.4.0                      py_0
attrs                     21.2.0             pyhd3eb1b0_0
azure-core                1.12.0                     py_0    esri
azure-storage-blob        12.8.0                     py_0    esri
backcall                  0.2.0              pyhd3eb1b0_0
beautifulsoup4            4.9.3              pyha847dfd_0
black                     19.10b0                    py_0
blas                      1.0                         mkl
bleach                    3.3.0              pyhd3eb1b0_0
blinker                   1.4              py37haa95532_0
boost                     1.73.0          py37haa95532_11
bottleneck                1.3.2            py37h2a96729_1
brotlipy                  0.7.0           py37h2bbff1b_1003
cached-property           1.5.2                      py_0
cachetools                4.2.2              pyhd3eb1b0_0
catalogue                 1.0.0                    py37_0    esri
certifi                   2021.5.30        py37haa95532_0
cffi                      1.14.6           py37h2bbff1b_0
cftime                    1.0.0b1                  py37_0    esri
chardet                   4.0.0           py37haa95532_1003
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.0.1              pyhd3eb1b0_0
cloudpickle               1.6.0              pyhd3eb1b0_0
colorama                  0.4.4              pyhd3eb1b0_0
cppzmq                    4.4.1                         2    esri
cryptography              3.3.1                    py37_0    esri
cudatoolkit               10.1.243             h74a9793_0
cudnn                     7.6.5                cuda10.1_0
cycler                    0.10.0                   py37_0
cymem                     2.0.5            py37hd77b12b_0
cython                    0.29.24          py37hd77b12b_0
cython-blis               0.4.1                    py37_0    esri
cytoolz                   0.11.0           py37he774522_0
dask-core                 2021.8.1           pyhd3eb1b0_0
decorator                 5.0.9              pyhd3eb1b0_0
deep-learning-essentials  2.8                 arcgispro_5  [arcgispro]  esri
defusedxml                0.7.1              pyhd3eb1b0_0
despatch                  0.1.0                    py37_0    esri
entrypoints               0.3                      py37_0
et_xmlfile                1.0.1                   py_1001
fastai                    1.0.60                   py37_0    esri
fastcache                 1.1.0            py37he774522_0
fastprogress              0.2.3                    py37_0    esri
fasttext                  0.9.2            py37h74a9793_0    esri
filelock                  3.0.12             pyhd3eb1b0_1
flake8                    3.9.2              pyhd3eb1b0_0
freetype                  2.10.1                   vc14_0  [vc14]  esri
fsspec                    2021.7.0           pyhd3eb1b0_0
future                    0.18.2                   py37_0    esri
gast                      0.2.2                    py37_0
gdal                      2.3.3           arcgispro_py37_16747  [arcgispro]  esri
google-auth               1.21.3                     py_0
google-auth-oauthlib      0.4.4              pyhd3eb1b0_0
google-pasta              0.2.0              pyhd3eb1b0_0
googledrivedownloader     0.4                      py37_0    esri
graphviz                  2.38                 hfd603c8_2
grpcio                    1.35.0           py37hc60d5dd_0
h5py                      2.10.0          py37_arcgispro_10  [arcgispro]  esri
html5lib                  1.1                pyhd3eb1b0_0
icc_rt                    2019.0.5            arcgispro_0  [arcgispro]  esri
idna                      3.2                pyhd3eb1b0_0
imageio                   2.8.0                    py37_0    esri
importlib-metadata        3.10.0           py37haa95532_0
importlib_metadata        3.10.0               hd3eb1b0_0
iniconfig                 1.1.1              pyhd3eb1b0_0
intel-openmp              2020.0            arcgispro_166  [arcgispro]  esri
ipykernel                 5.1.1                    py37_0    esri
ipython                   7.21.0                   py37_0    esri
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                7.4.2                    py37_0
isodate                   0.6.0                      py_0    esri
jdcal                     1.4.1                      py_0
jedi                      0.18.0                   py37_0    esri
jinja2                    2.11.3             pyhd3eb1b0_0
joblib                    1.0.1              pyhd3eb1b0_0
jpeg                      9d                            0    esri
json5                     0.9.4                    py37_0    esri
jsonschema                3.2.0              pyhd3eb1b0_2
jupyter_client            6.1.7                      py_0    esri
jupyter_console           6.2.0                      py_2    esri
jupyter_contrib_core      0.3.3                    py37_3    esri
jupyter_contrib_nbextensions 0.5.1                   py37_10    esri
jupyter_core              4.6.3                    py37_2    esri
jupyter_highlight_selected_word 0.2.0                    py37_2    esri
jupyter_latex_envs        1.4.4                    py37_1    esri
jupyter_nbextensions_configurator 0.4.1                    py37_1    esri
jupyterlab                2.2.7                      py_0    esri
jupyterlab_server         1.2.0                      py_0
keepalive                 0.5                      py37_1    esri
keras-applications        1.0.8                      py_1
keras-base                2.3.1                    py37_0
keras-gpu                 2.3.1                         0
keras-preprocessing       1.1.2              pyhd3eb1b0_0
keyring                   21.4.0                   py37_0    esri
kiwisolver                1.3.1            py37hd77b12b_0
laspy                     1.7.0                    py37_1    esri
lerc                      3.0                pyh39e3cac_0    esri
libboost                  1.73.0              h6c2663c_11
libopencv                 4.5.0                    py37_4    esri
libpng                    1.6.37               h2a8f88b_0
libprotobuf               3.17.2               h23ce68f_1
libsodium                 1.0.18                        1    esri
libtiff                   4.1.0                         0    esri
libwebp                   1.2.0                h2bbff1b_0
libxml2                   2.9.10              arcgispro_0  [arcgispro]  esri
libxslt                   1.1.34               he774522_0
llvmlite                  0.36.0           py37h34b8924_4
locket                    0.2.1            py37haa95532_1
lxml                      4.6.3            py37h9b66d53_0
lz4-c                     1.9.3                h2bbff1b_1
markdown                  3.3.4            py37haa95532_0
markupsafe                1.1.1            py37hfa6e2cd_1
matplotlib                3.3.1           py37_arcgispro_0  [arcgispro]  esri
mccabe                    0.6.1                    py37_1
mistune                   0.8.4           py37hfa6e2cd_1001
mkl                       2020.0            arcgispro_167  [arcgispro]  esri
mkl-service               2.3.0            py37h196d8e1_0
mkl_fft                   1.3.0            py37h46781fe_0
mkl_random                1.2.0                    py37_0    esri
mpmath                    1.2.1            py37haa95532_0
msrest                    0.6.21                     py_0    esri
murmurhash                1.0.5            py37hd77b12b_0
mypy_extensions           0.4.3                    py37_0
nbconvert                 5.6.1                    py37_0    esri
nbformat                  5.0.7                      py_1    esri
netcdf4                   1.5.4           py37_arcgispro_6  [arcgispro]  esri
networkx                  2.5                      py37_0    esri
ninja                     1.10.2               h6d14046_1
nlohmann_json             3.7.0                         1    esri
nose                      1.3.7           pyhd3eb1b0_1006
notebook                  5.7.10                   py37_0
ntlm-auth                 1.4.0                      py_0    esri
numba                     0.53.0           py37hf11a4ad_0
numexpr                   2.7.3            py37hcbcaa1e_0
numpy                     1.20.1                   py37_0    esri
numpy-base                1.20.1                   py37_0    esri
nvidia-ml-py3             7.352.0                    py_0    esri
oauthlib                  3.1.1              pyhd3eb1b0_0
olefile                   0.46                     py37_0
onnx                      1.7.0                    py37_1    esri
onnx-tf                   1.5.0                    py37_2    esri
opencv                    4.5.0                    py37_4    esri
openpyxl                  3.0.7              pyhd3eb1b0_0
openssl                   1.1.1i                        0    esri
opt_einsum                3.3.0              pyhd3eb1b0_1
packaging                 21.0               pyhd3eb1b0_0
pandas                    1.3.2            py37h6214cd6_0
pandocfilters             1.4.3            py37haa95532_1
parso                     0.8.1              pyhd3eb1b0_0
partd                     1.2.0              pyhd3eb1b0_0
pathspec                  0.7.0                      py_0
pefile                    2019.4.18                  py_0
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow-simd               8.2.0                    py37_1    esri
pip                       21.2.2           py37haa95532_0
plac                      1.1.0                    py37_1
plotly                    4.5.4                      py_0    esri
pluggy                    0.13.1           py37haa95532_0
pooch                     1.0.0                    py37_0    esri
preshed                   3.0.2                    py37_0    esri
pro_notebook_integration  2.8                      py37_0    esri
prometheus_client         0.8.0                      py_0    esri
prompt_toolkit            3.0.5                      py_0    esri
protobuf                  3.17.2           py37hd77b12b_0
psutil                    5.8.0            py37h2bbff1b_1
py                        1.10.0             pyhd3eb1b0_0
py-boost                  1.73.0          py37hac22706_11
py-opencv                 4.5.0                    py37_4    esri
pyarrow                   1.0.1                         1    esri
pyasn1                    0.4.8              pyhd3eb1b0_0
pyasn1-modules            0.2.8                      py_0
pybind11                  2.3.0                         1    esri
pycodestyle               2.7.0              pyhd3eb1b0_0
pycparser                 2.20                       py_2
pyflakes                  2.3.1              pyhd3eb1b0_0
pygments                  2.7.0                      py_0    esri
pyjwt                     2.1.0            py37haa95532_0
pyopenssl                 20.0.1             pyhd3eb1b0_1
pyparsing                 2.4.7              pyhd3eb1b0_0
pypdf2                    1.26.0                     py_2    esri
pyrsistent                0.17.3           py37he774522_0
pyshp                     2.1.3              pyhd3eb1b0_0
pysocks                   1.7.1                    py37_1
pytest                    6.1.1                    py37_0    esri
python                    3.7.10                        0    esri
python-certifi-win32      1.2                      py37_0    esri
python-dateutil           2.8.2              pyhd3eb1b0_0
pytorch                   1.4.0           py3.7_cuda101_cudnn7_0    esri
pytz                      2020.1                   py37_0    esri
pywavelets                1.1.1            py37he774522_2
pywin32-ctypes            0.2.0                    pypi_0    pypi
pywin32-security          228                      py37_3    esri
pywinpty                  0.5.7                    py37_0    esri
pyyaml                    5.4.1            py37h2bbff1b_1
pyzmq                     19.0.2                   py37_1    esri
rdflib                    5.0.0                    py37_0    esri
regex                     2021.8.3         py37h2bbff1b_0
requests                  2.26.0             pyhd3eb1b0_0
requests-kerberos         0.12.0                        0    esri
requests-negotiate-sspi   0.5.2                    py37_1    esri
requests-oauthlib         1.3.0                      py_0
requests-toolbelt         0.9.1                      py_0
requests_ntlm             1.1.0                      py_0    esri
retrying                  1.3.3                    py37_2
rsa                       4.7.2              pyhd3eb1b0_1
sacremoses                0.0.43                     py_0    esri
saspy                     3.6.1                      py_0    esri
scikit-image              0.17.2                   py37_1    esri
scikit-learn              0.23.2           py37h47e9c7a_0
scipy                     1.6.2            py37h14eb087_0
send2trash                1.5.0              pyhd3eb1b0_1
sentencepiece             0.1.91           py37h74a9793_0    esri
setuptools                52.0.0           py37haa95532_0
simplegeneric             0.8.1                    py37_2
six                       1.15.0                     py_0    esri
soupsieve                 2.2.1              pyhd3eb1b0_0
spacy                     2.2.4                    py37_0    esri
sparqlwrapper             1.8.5                    py37_1    esri
sqlite                    3.36.0               h2bbff1b_0
srsly                     1.0.2                    py37_0    esri
swat                      1.8.1                    py37_0    esri
sympy                     1.5.1                    py37_0    esri
tensorboard               2.4.0              pyhc547734_0
tensorboard-plugin-wit    1.6.0                      py_0
tensorboardx              2.1                        py_0    esri
tensorflow                2.1.0           gpu_py37h7db9008_0
tensorflow-addons         0.9.1                    py37_1    esri
tensorflow-base           2.1.0           gpu_py37h55f5790_0
tensorflow-estimator      2.5.0              pyh7b7c402_0
tensorflow-gpu            2.1.0                h0d30ee6_0
termcolor                 1.1.0            py37haa95532_1
terminado                 0.9.3            py37haa95532_0
testpath                  0.4.4              pyhd3eb1b0_0
thinc                     7.4.0                    py37_0    esri
threadpoolctl             2.2.0              pyh0d69192_0
tifffile                  2020.10.1        py37h8c2d366_2    esri
tokenizers                0.10.1                   py37_0    esri
toml                      0.10.2             pyhd3eb1b0_0
toolz                     0.11.1             pyhd3eb1b0_0
torch-cluster             1.5.4                    py37_1    esri
torch-geometric           1.5.0                    py37_4    esri
torch-scatter             2.0.4                    py37_2    esri
torch-sparse              0.6.1                    py37_1    esri
torch-spline-conv         1.2.0                    py37_1    esri
torchvision               0.5.0                py37_cu101    esri
tornado                   6.1              py37h2bbff1b_0
tqdm                      4.62.1             pyhd3eb1b0_1
traitlets                 4.3.3                    py37_0
transformers              3.3.0                      py_1    esri
typed-ast                 1.4.3            py37h2bbff1b_1
typeguard                 2.7.0                    py37_0    esri
typing_extensions         3.10.0.0           pyhca03da5_0
ujson                     4.0.2            py37hd77b12b_0
urllib3                   1.26.6             pyhd3eb1b0_1
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_0    esri
wasabi                    0.6.0                    py37_0    esri
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py37_1
werkzeug                  0.16.1                     py_0
wheel                     0.37.0             pyhd3eb1b0_1
widgetsnbextension        3.4.2                    py37_0
win_inet_pton             1.1.0                    py37_0    esri
wincertstore              0.2                      py37_0
winkerberos               0.7.0                    py37_0    esri
winpty                    0.4.3                         4
wrapt                     1.12.1           py37he774522_1
x86cpu                    0.4                      py37_1    esri
xarray                    0.17.0             pyhd3eb1b0_0
xeus                      0.24.1                        1    esri
xlrd                      1.2.0                    py37_0
xlwt                      1.3.0                    py37_0
xtl                       0.6.5                         1    esri
xz                        5.2.5                h62dcd97_0
yaml                      0.2.5                         0    esri
zeromq                    4.3.2                         2    esri
zipp                      3.5.0              pyhd3eb1b0_0
zlib                      1.2.11               h62dcd97_4
zstd                      1.4.5                h04227a9_0

thanks
ty

**Comment by scdub** [comment]
@tyhayward were you able to address this? If not, you should be able to run `conda upgrade pyarrow` to get a build which addresses the issue. Unfortunately, pandas shipped an update which expected a specific behavior from `pyarrow` which wasn't present in our build.

**Comment by taitlw** [comment]
thanks for the post @tyhayward and the solution from @scdub worked for me
