### ISSUE TITLE
Updating deep learning frameworks to new version

### ISSUE THREAD

**Issue by Antwark** [Esri/deep-learning-frameworks#32]
Previously, I installed the deep learning frameworks on my workstation using the installer for Pro 2.6 (the installer provided by Esri that installs all the stuff, which is great!). It is up and running. and I could train models, infere and so on, without many problems.

The question is: I want to upgrade Pro to the last version compatible with the last deep learning frameworks installer. What strategy do you suggest? Upgrade first Pro and then uninstall the previous frameworks? Uninstall the previos frameworks before upgrading Pro? Upgrade Pro and then install the new frameworks on top of the old ones?

Any guidance about the order of installs and how to proceed will be appreciated. Thanks!!! 

p.s.: for uninstalling the AI frameworks I suppose that the old installer has an uninstall procedure under programs >> uninstall, right?

**Comment by scdub** [comment]
@Antwark I've added an additional section to the installation instructions, "Upgrading From a Previous Version" which should give you details about the upgrade procedure. Let us know if anything there isn't clear!
