### ISSUE TITLE
Instability with ArcGIS Pro Python env after installing deep learning framework

### ISSUE THREAD

**Issue by tri11103** [Esri/deep-learning-frameworks#42]
I've been working on a Python toolbox (https://github.com/tri11103/CreateLRSEventsFromStreetLevelImagery) that utilizes the deep learning capabilities in ArcGIS Pro 2.9. Since installing the framework, I've noticed some strange behavior. I've had the Pro crash when I open the Python tool in the Geoprocessing pane, and I've also had it crash as soon as I press the Run button in the Geoprocessing pane. Sometimes... it works totally fine. It seems totally random where it's going to crash--it seems like a 50/50 chance that it might crash in either scenario even after rebooting/reinstalling Pro. 

I'm able to run the tool using the Python window and as a standalone Python script. Whatever is causing it to crash Pro seems to be either related to the deep learning framework or something with the core Geoprocessing engine. I believe it's the former, as I've worked with other custom built Python toolboxes prior to installing the deep learning framework and did not see this behavior. 

Is this something that the team is aware of? Is there a workaround?

**Comment by scdub** [comment]
Closing this as we've identified that it isn't an issue with the DL installer but a bug in the GP framework that will be addressed.
