### ISSUE TITLE
ArcGIS Pro (with deep learning libraries) - problem with "Evaluate Point Cloud Classification Model"

### ISSUE THREAD

**Issue by AlbertoPossa** [Esri/deep-learning-frameworks#43]
Goodmorning,
I am a student of the Politecnico di Torino. For my master's thesis I am working with the deep learning library on ArcGIS Pro. The aim of my work is to classify a point cloud of an urban area.

After having prepared the 3 clouds of Training, Validation and Test, I have followed the 4 steps provided by ArcGIS Pro to classify a point cloud:

Prepare Point Cloud Training Data
Train Point Cloud Classification Model
Evaluate Point Cloud Classification Model
Classify Point Cloud Using Trained Mode
The problem is in the third step. In "Input Model Definition" I should insert the files with the extension .emd and .dlpk which are generated by the previous step 2 (Train Point Cloud Classification Model). When I enter the settings in the "Evaluate Point Cloud Classification Model" command, 2 errors appear: ERROR 000241 and ERROR 050174 (attached images) of ArcGIS Pro.

![ERROR 000241](https://user-images.githubusercontent.com/100772002/157232391-00613cbb-bf96-42bc-9e8a-d853c0f690fb.jpg)
![ERROR 050174](https://user-images.githubusercontent.com/100772002/157232393-264cbd16-1a31-4a01-8401-ea46003251a8.jpg)

In "Input Model Definition" I should insert the files with the extension .emd and .dlpk which are generated by the previous step 2 (Train Point Cloud Classification Model). These 2 files are not found by the software (ERROR 00241) and in "Point Cloud Class Remapping" ERROR 050174 I think says that there are no classifications in the point cloud.

I do not understand why this command does not work, also because up to 2 months ago I had done the whole procedure without any problems.

I have contacted ESRI technical support but they claim that it is not their responsibility because the deep learning libraries were created by third parties. Is this correct?
They replied me with the following 2 links where the procedure for installing your library is presented.
https://www.esri.com/arcgis-blog/products/arcgis-pro/imagery/deep-learning-with-arcgis-pro-tips-tricks/
https://www.esri.com/arcgis-blog/products/arcgis-pro/mapping/deep-learning-with-arcgis-pro-tips-tricks-part-2/
We followed the procedure described in the first link and we couldn't even finish it because the step "Installing the dependencies on a cloned Python environment" didn't work.

Can you help me?

Below are some characteristics of the software and the PC I use:

ArcGIS Pro 2.9.0 (I also tried with the new update to version 2.9.2, but the problem remains)
NVIDIA Quadro M2000 GPU, CUDA 5.2 (https://www.nvidia.com/content/dam/en-zz/Solutions/design-visualization/documents/38111-DS-NV-Quadro-M2000-Feb16-US-NV-Fnl-HR.pdf) (https://en.wikipedia.org/wiki/CUDA#GPUs_supported)
Now I'm going to try to install the ArcGIS Pro 2.6, 2.7 and 2.8 versions with the deep learning libraries related to the software version to see if it works or not.

I am available for any questions or information.

I hope you can solve my problem.

Thank you

**Comment by scdub** [comment]
@AlbertoPossa Were you able to address this issue? I'm sorry for our delay in responding to you. I have reached out to support to ensure that issues like this are reported through that mechanism as expected.
