### ISSUE TITLE
Password 

### ISSUE THREAD

**Issue by Lumble01** [Esri/deep-learning-frameworks#45]
It's asking for username and password while I was downloading the framework for arcgis pro 2.8

**Comment by cleebp** [comment]
Hi, could you please provide more information about your issue? I just [downloaded](https://github.com/Esri/deep-learning-frameworks/releases) ArcGIS Pro 2.8 Deep Learning Essentials and was not asked for a username/password by GitHub to start the download. Are you being asked for a user/pass in Pro itself? In that case you will need to sign in and authorize your Pro installation.

**Comment by cleebp** [comment]
Closing as not an issue.
