### ISSUE TITLE
Classify objects and pixels are not working properly in ArcGIS pro 2.7

### ISSUE THREAD

**Issue by hafez-ahmad** [Esri/deep-learning-frameworks#47]
I am using ArcGIS pro 2.7. At first , generate labels using 'label objects for deep learning', then I export them and I train models. All these steps are working fine. But when then I try to use 'Classify pixels' it return same raster without classifying pixels and 'classify object' return errors message . I don't know why this is happening.  
![image](https://user-images.githubusercontent.com/20365917/164319229-c0290fb6-5429-4a9b-9340-ff841d7866e0.png)

**Comment by cleebp** [comment]
Hi @hafez-ahmad - I think this was an issue with the Classify Pixel (inference) tools in older Pro versions, you may have success if you uninstall and upgrade to Pro 2.9 and install the 2.9 deep learning installer, just make sure to uninstall your current version of the deep learning installer via Add or Remove Programs before installing 2.9.

**Comment by scdub** [comment]
@hafez-ahmad There are a number of enhancements that have gone into this tool in Pro 2.8&mdash;3.0 that likely have addressed this issue. If you continue to have problems with a current Pro release like 2.9 or 3.0, we can dig further.
