### ISSUE TITLE
Installation of other external python libraries failed

### ISSUE THREAD

**Issue by MirandaLv** [Esri/deep-learning-frameworks#48]
After updating my ArcGISpro to the most recent version 2.9 and following the instruction of installing the deep learning framework, I cannot install the external python libraries such as rasterio, geopandas as others. There is no errors or message reminding you the fail installation if adding the packages from the python package manager. Errors and warnings of conflicts packages pops up if installing rasterio or geopandas through conda or python command prompt. 

Any suggestions on how to solve the conflicts?

**Comment by MirandaLv** [comment]
Hey, I just wanna follow up and see if there is any updates? Thanks.

**Comment by scdub** [comment]
Hi @MirandaLv,

I did take a quick look at this, and was able to install `rasterio` and `geopandas` into a separate cloned environment at 2.9. Unfortunately, neither `torchgeo` or `pytorch_lightning` is available in the default channel set (only on conda-forge) and they have an extensive set of dependencies that may be some work to harmonize with what this package provides. A starting point might be creating a separate environment, with just those packages and Python 3.7, e.g.:

    conda create -n geolighting -c conda-forge torchgeo python=3.7

Then see if you can do `conda install deep-learning-essentials` into that environment. It is possible that we will need to do some additional work providing specific builds of shared dependencies to make everything compatible, this would be an enhancement request that we can get logged in that case. As a shorter term option, I would see if in a cloned environment you can `pip` install just torchgeo, which depends on lightning and everything else below it. If that works, at least you're in business in the short term.

**Comment by MirandaLv** [comment]
Thanks Shaun! I will try it out. Would this "conda create -n geolighting -c conda-forge torchgeo python=3.7" also install the arcgis environment as well? I also need to use some of arcpy's functions for my toolbox.

**Comment by scdub** [comment]
> Thanks Shaun! I will try it out. Would this "conda create -n geolighting -c conda-forge torchgeo python=3.7" also install the arcgis environment as well? I also need to use some of arcpy's functions for my toolbox.

You could update it to `conda create -n geolighting -c conda-forge torchgeo python=3.7 arcpy=2.9` and it'll pull in the requirements for ArcPy, if there aren't any conflicts (hopefully!)

**Comment by MirandaLv** [comment]
Cool! I will try it out, thanks!

**Comment by scdub** [comment]
@MirandaLv if this is still an issue, let us know! Assuming it is working and closing this out, but we can reopen and log something internally if there are changes we need to make.
