### ISSUE TITLE
160676: The domain name is invalid.

### ISSUE THREAD

**Issue by pooya-rezvan** [Esri/deep-learning-frameworks#49]
Hello, 
I face this error just as I start the tool "detecting object for DL".
I noticed that another user had the same problem, but the ticket was closed.
I am using ArcGIS Pro 2.7 and all the required modules are already installed and my GPU is working well.

Thank you so much,
Pooya

![image](https://user-images.githubusercontent.com/107805013/174488772-d44691c2-6fa2-4df3-a479-6947ae260422.png)

**Comment by pooya-rezvan** [comment]
I also tried to do it with ArcPy, but I got the same error message!

![image](https://user-images.githubusercontent.com/107805013/175425336-731ff711-5a95-41d5-8f09-fe5e764c3642.png)

**Comment by pooya-rezvan** [comment]
Ok, I figured it out myself.
It was related to the "class name" that the ArcGIS assigns to each class value for the object detection.

**Comment by scdub** [comment]
@pooya-rezvan glad you figured it out! Will close this issue, let us know if you run into anything else.
