### ISSUE TITLE
Deep Learning ArcGIS Pro 3.0

### ISSUE THREAD

**Issue by jplunkett1** [Esri/deep-learning-frameworks#51]
Hi there can you please let me know when the Deep Learning ArcGIS Pro 3.0 modules will be available for download?
Many thanks

**Comment by akendall8969** [comment]
Any update on when 3.0 will be available?

**Comment by mastereotype** [comment]
When will the module be uploaded ? Exact date

**Comment by xabierr** [comment]
Tried cloning the environment and manually re-installing the libraries but didnt work. Are the 3.0 libraries coming anytime soon? Thanks

**Comment by Waqar82geo** [comment]
> Tried cloning the environment and manually re-installing the libraries but didnt work. Are the 3.0 libraries coming anyti

**Comment by Waqar82geo** [comment]
Must be available with the launch of 3.0 pro

**Comment by BoudewijnBoogaard** [comment]
> Yes they should be available this week 🤞 I'll reply on here and close this issue once the download links are posted on the readme.
> 
> In the meantime if you need to get going with deep learning in Pro 3.0 you can follow the manual developer install steps to get a cloned environment with all of the pro 3.0 deep learning libraries installed, instructions are here: https://github.com/Esri/deep-learning-frameworks#developer-install-steps

Any updates on this?

**Comment by scdub** [comment]
@BoudewijnBoogaard 
> Any updates on when it will be available?

They should be released later today.

**Comment by scdub** [comment]
> Must be available with the launch of 3.0 pro

That of course would be the ideal. We will be working toward it, but there are limitations similar to language packs which can push the released date past when Pro itself is available.

**Comment by jplunkett1** [comment]
Hi all - it looks like the 3.0 is now there. - Thanks for releasing this :) - Ill close the thread.

**Comment by scdub** [comment]
@jplunkett1 thanks for your patience!
