### ISSUE TITLE
Download slows down to 30-45KB/s

### ISSUE THREAD

**Issue by widsuoids** [Esri/deep-learning-frameworks#52]
https://gisupdates.esri.com/DeepLearning/Pro/ArcGIS_Pro_30_Deep_Learning_Libraries.zip
https://gisupdates.esri.com/DeepLearning/Server/11.0/ArcGIS_Server_11_Deep_Learning_Libraries.zip
![image](https://user-images.githubusercontent.com/112546295/187638989-7351b31b-9644-4b75-a0f2-66508a587f2d.png)

Downloads from gisupdates.esri.com sometimes slow down to 30-45KB/s. Please provide alternative Download location.

This is not caused by my internet connection, I have 300Mbps.

**Comment by scdub** [comment]
I've reached out to an internal team to see if they can provide any details. What part of the world are you located in? Previously we had hosted our files directly on GitHub as GitHub releases, but that mechanism has a limit of 2GB and the installers exceed this size.

**Comment by scdub** [comment]
Without further information we're unable to do anything about this, but if you're still running into issues and can provide some additional details we can reopen the issue.
