### ISSUE TITLE
ArcGIS Pro 3.0.1 RTX 3060 TI Detect Objects (deep learning error)

### ISSUE THREAD

**Issue by BenLim88** [Esri/deep-learning-frameworks#53]
I recently upgraded to ArcGIS Pro 3.0.1 to use the Deep Learning tools with RTX 3060Ti. I heard that it was resolved from 2.9 onwards (i.e. CUDA 11 support) so I was excited to give it a go. I'm running CUDA 11.7, NVIDIA-SMI 516.94, Driver Version: 516.94 (latest drivers)

I did a clean install of ArcGIS Pro 3.0.1, followed by the Deep Learning Package for ArcGIS Pro 3.0. 

The pipeline of MaskRCNN, from Creating Samples to Exporting Training Data to Train Deep Learning Model went without a hitch using GPU. Previously I had to use CPU on ArcGIS Pro 2.8.X and now the training is much faster.

The problem comes when I tried to perform the inferencing using the Detect Objects tool. The following ERROR 999999 comes up.

![image](https://user-images.githubusercontent.com/29766270/188895110-94ed688a-2260-4227-8375-29df14ee386c.png)

However, if I set the Processor Type to CPU, the inference works, though slow.

UPDATE*

It seems to be a known problem here: [Problem: Unable to execute the Detect Objects Using Deep Learning tool in ArcGIS Pro (esri.com)](https://support.esri.com/en/technical-article/000025535). But I tried the solution to no avail (i.e. Parallel Processing value)

Another reported one was: [Solved: Detect Object Using Deep Learning Error 999999 Whe... - Esri Community](https://community.esri.com/t5/arcgis-pro-questions/detect-object-using-deep-learning-error-999999/td-p/1089098). Thing is my ArcGIS Pro is already 3.0.1.

Also, I only have a single RTX 3060Ti card in the computer.

Appreciate any advice please.

**Comment by scdub** [comment]
@BenLim88 Can you log this issue with support? They're probably in the best position to get your details to the team that developed this tool and a private way to share your data and use case. I don't see any open issues logged with Pro 3.0 that would create this, and I think the original issue was addressed, so there is probably some other circumstance than parallel processing factor causing the failure, despite sharing the same error message. I can try the same model locally if you want to share the model and data here rather than support.

**Comment by scw** [comment]
This issue may have been addressed in Pro 3.1 or the recently release Pro 3.2. If you still have an issue, please log it through support, thanks!

**Comment by Chunchaodong** [comment]
Hi, I hope you don't mind me asking — I’m currently experiencing a similar error and was wondering if you were able to resolve the issue. I’m using ArcGIS Pro 3.3 with an NVIDIA 4060 Laptop GPU. Any insights or suggestions would be greatly appreciated. Thank you in advance!
