### ISSUE TITLE
Which license do I need to activate the deep learning toolbox?

### ISSUE THREAD

**Issue by philipperemy** [Esri/deep-learning-frameworks#59]
https://skysense1.maps.arcgis.com/home/organization.html?#licenses

![image](https://user-images.githubusercontent.com/4516927/215236881-002f0b88-c705-4a09-bcd5-f35df4f9aa00.png)

Thanks!

**Comment by scdub** [comment]
If you visit Settings > Licensing, you'll see the Esri Extensions licensed for your account. Can you check if you have the Image Analyst extension tied to your account? [This document](https://pro.arcgis.com/en/pro-app/latest/tool-reference/image-analyst/an-overview-of-the-deep-learning-toolset-in-image-analyst.htm) has the full list of tools tied to Image Analyst, typically an organization administrator controls what licenses are tied to each organization account.

**Comment by philipperemy** [comment]
@scdub thank you it works!

**Comment by scdub** [comment]
@philipperemy Great! I also [added a brief section](https://github.com/Esri/deep-learning-frameworks#tool-requirements) to the README including the licensing information.
