### ISSUE TITLE
Error 002667 encountered while performing deep learning detection of targets on arcgispro version 3.0.2 with a 3060 graphics card

### ISSUE THREAD

**Issue by leijiang1122** [Esri/deep-learning-frameworks#62]
<img width="592" alt="微信图片_20230213161015" src="https://user-images.githubusercontent.com/125251626/218404488-73f94c74-7a86-42fb-bd0d-63a8d52c5d4e.png">
<img width="716" alt="微信截图_20230213155630" src="https://user-images.githubusercontent.com/125251626/218404517-10f7f1e1-58da-4b6c-8c54-fa3a9bb4d866.png">
Deep-learning-frameworks, CUDA11.2, cuDNN11.0 are correctly installed
Environment is win11, 3060laptop6G, 16gRAM, I7 12700H ArcGISPro3.0.2
It is worth noting that it runs properly when training the deep-learning model
<img width="210" alt="微信截图_20230213160849" src="https://user-images.githubusercontent.com/125251626/218403888-bab703ff-03b5-4977-8696-d35c30389a23.png">

**Comment by leijiang1122** [comment]
@scdub I look forward to hearing from you!

**Comment by ezw21** [comment]
Hi there, can you try cloning another conda environment with the deep learning essentials downgraded to 2.8 / 2.9 dependencies? That might helps.

**Comment by scdub** [comment]
@ezw21 In most cases, this will cause issues as the package sets are tied to the product versions in terms of testing and what the tool expects.

@leijiang1122 Can you try rerunning the tool at a location with a short path with only ASCII characters? It is possible one of the tiers of the stack is failing to be Unicode aware and not correctly passing the inputs through the system. If that fails, it at least tells us to look elsewhere.

**Comment by leijiang1122** [comment]
![image](https://github.com/Esri/deep-learning-frameworks/assets/125251626/84dffcf6-db7e-4676-a9b1-e5a53c856a11)
002667 has been resolved, but there is a new problem error999999

**Comment by scdub** [comment]
@leijiang1122 Please report this issue to Esri support, unfortunately the tool internals aren't visible from this traceback, but I do see other issues logged related to this.
