### ISSUE TITLE
Unable to see all packages in ArcGIS Pro interface after installation of Deep Learning Framework

### ISSUE THREAD

**Issue by JosephKlangDOT** [Esri/deep-learning-frameworks#67]
I was able to successfully install the Deep Learning Framework, so it appeared. No issues or errors. I can see all of the packages listed in the default environment at this location - C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages. However, in the ArcGIS Pro Package Manager interface, I do not see all of the packages that should have been added via this install. Examples include:

- fastai
- pycocotools
- mmdet
- addict

Did these packages that I do not see in the ArcGIS Pro Package Manager interface not get installed correctly? 

This is ArcGIS Pro version 3.1. 

Thank you!!

**Comment by JosephKlangDOT** [comment]
They do show up in conda list. Looks like it is just UI specific.

**Comment by scdub** [comment]
Thanks for the confirmation. I've included your notes in an existing issue for the UI bug. Because that bug is for Pro not the deep learning packages specifically, I'll close this but update this issue once the fix is installed into Pro.
