### ISSUE TITLE
ArcGIS Pro 3.1 crashes when using Detect Objects Using Deep Learning tool

### ISSUE THREAD

**Issue by johnsonc-EsriCA** [Esri/deep-learning-frameworks#68]
Fresh install of Pro 3.1 and associated version of the deep learning libraries. Trying to run "Detect Objects Using Deep Learning" and Pro crashes out/shuts down almost right away after adding in a DLPK file. I am wondering if it's because my CPU is AMD instead of Intel.  My specs:

OS: Windows 11
CPU: AMD Ryzen 7 3700X
RAM: 32GB
GPU: NVIDIA GeForce RTX 3060 Ti

Any advise would be appreciated!

**Comment by kalng62** [comment]
I have the same issue. And I don't think it's the problem of the cpu since I m using intel 7 12700k with same os.

**Comment by scw** [comment]
If you submit crash dumps, those will get routed to the appropriate team for evaluation. It may be issues with the deep learning packages themselves, but also can be issues in the Pro codebase interacting with those libraries. Unfortunately, without those crash dumps there isn't an immediate step I can help you with here, I'd recommend checking that you have a clean environment with packages installed just from conda and that your `%APPDATA%\Python39\site-packages` directory has no entries, e.g. you're not being impacted by a global pip cache.
