### ISSUE TITLE
 ArcGIS Pro 3.0.2 RTX A4000 -Classify Pixels using deep learning error 

### ISSUE THREAD

**Issue by kuihua1985** [Esri/deep-learning-frameworks#69]
ArcGIS Pro 3.0.2；
GPU：RTX A4000；
CUDA >11.0;
NVIDIA driver updated to the latest;

training tool works well, and classify pixels using deep learning processed using CPU successfully, bur processed using GPU faild.
Sometimes no error was reported, while the result data  blank. sometimes failed with a generic error 999999.

**Comment by leijiang1122** [comment]
I'm having the same problem, which I'm told can be avoided by using a genuine license

**Comment by kuihua1985** [comment]
> I'm having the same problem, which I'm told can be avoided by using a genuine license

Thanks. We've  solved this issue by upgrading ArcGIS Pro to version 3.1.

**Comment by kuihua1985** [comment]
> I'm having the same problem, which I'm told can be avoided by using a genuine license

Thanks.
