### ISSUE TITLE
Deep Learning instalators for 2.7 Alpha

### ISSUE THREAD

**Issue by holubvl3** [Esri/deep-learning-frameworks#7]
Dear @scw ,

would it be possible to upload to EAC a vesrion for 2.7? The 2.6 installer requires 2.6 and it does not work with 2.7.

The manual installation ending on the error - ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'anaconda::attrs-20.1.0-py_0'.  

Thank you.

**Comment by scdub** [comment]
@holubvl3 For Pro 2.7 builds, the current easiest way is to run `conda install deep-learning-essentials` in a cloned environment -- the installer for the Pro 2.7 specific versions will be added in conjunction with the final release of 2.7.

Cheers, Shaun

**Comment by holubvl3** [comment]
@scdub Thank you very much, this is cool workaround!

Regards,

Vladimir

**Comment by scdub** [comment]
This issue has been addressed with the final release of the Pro 2.7 installer, the Server installers will be available with the 10.9 release. Cheers
