### ISSUE TITLE
Error got when trying clone the arcgispro-py3

### ISSUE THREAD

**Issue by MirandaLv** [Esri/deep-learning-frameworks#70]
Hi,

I have the ArcGIS Pro3.1.0 installed, and then installed the deep learning installer on my computer. In order to use some third party python library, I try to clone the default arcgispro-py3, but I kept receiving below errors. Is there any way to properly clone the default working environment? Thanks.

InvalidArchiveError("Error with archive C:\\Users\\mlv\\AppData\\Local\\ESRI\\conda\\pkgs\\tensorflow-base-2.7.0-py39_cuda11.1_cudnn8.1_6.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message was:\n\nfailed with error: [WinError 206] The filename or extension is too long: 'C:\\\\Users\\\\mlv\\\\AppData\\\\Local\\\\ESRI\\\\conda\\\\pkgs\\\\tensorflow-base-2.7.0-py39_cuda11.1_cudnn8.1_6\\\\Lib\\\\site-packages\\\\tensorflow\\\\include\\\\external\\\\cudnn_frontend_archive\\\\_virtual_includes\\\\cudnn_frontend\\\\third_party\\\\cudnn_frontend\\\\include\\\\contrib\\\\nlohmann\\\\json'")

**Comment by armstrys** [comment]
I also ran into this exact same error this morning when attempting to clone an existing arcpro environment with the deep learning libraries installed.

**Comment by MirandaLv** [comment]
Thanks for pointing out the resource!

**Comment by scw** [comment]
This has been addressed with the Pro 3.2 installers. Thanks for the report!
