### ISSUE TITLE
ArcGIS Pro 3.1 toolbox arcpy.ia.DetectObjectsUsingDeepLearning() Bug Error

### ISSUE THREAD

**Issue by dericktrinidad** [Esri/deep-learning-frameworks#71]
I am trying to create a python script to automate the "Detect Objects Using Deep Learning" tool box. I have deduced that my error comes from running the following python command:
with arcpy.EnvManager(processorType="GPU"):
out_classified_raster = arcpy.ia.DetectObjectsUsingDeepLearning(
in_raster="tw-a_resized.png",
out_detected_objects=save_output_raster_path,
in_model_definition = pre_trained_model,
arguments="padding 56;batch_size 4;threshold 0.9;return_bboxes False;test_time_augmentation False;merge_policy mean;tile_size 224",
run_nms="NO_NMS",
confidence_score_field="Confidence",
class_value_field="Class",
max_overlap_ratio=0,
processing_mode="PROCESS_AS_MOSAICKED_IMAGE"
)
out_classified_raster.save(None)
(I just copied the python command from the geoprocessing window.)
DetectObjectsUsingDeepLearning tool worked, it was able to classify my raster no issues
but at the end of the code I get the following error:
AttributeError: 'ArcGISInstanceDetector' object has no attribute 'updatePixels'
Failed to execute (Tool).

This error is only caused by executing 'DetectObjectsUsingDeepLearning' through arcgis scripts. I've tested the 'DetectObjectsUsingDeepLearning' tool (through the geoprocessing window) and it works with no errors. Is there a way to patch and fix this bug so my script doesn't error? Alternatively, is there a way to force my python script to succeed if it classifies the raster with no issues?
Screen Shot of Error:
![Screenshot 2023-09-12 145522](https://github.com/Esri/deep-learning-frameworks/assets/51333368/1234a6ba-454e-4079-a0a9-3929d75c5e87)
Screen Shot of Results:
'DetectObjectsUsingDeepLearning' is classifying objects as intended but I am still getting this unknown error...

![Screenshot 2023-09-12 145708](https://github.com/Esri/deep-learning-frameworks/assets/51333368/602525c0-5155-4ff0-8538-2025e36c5c0d)

**Comment by scw** [comment]
Is your issue reproducible with Pro 3.3? I don't think based on the description it is an issue with the installers or the package set, if it is reproducible please log a support case for it.
