### ISSUE TITLE
ArcGIS Pro 3.2 Deep Learning Not recognized in package

### ISSUE THREAD

**Issue by toralero** [Esri/deep-learning-frameworks#75]
Hi! 
I'm using AcGIS pro 3.2 and the latest Deep learning Libraries also for 3.2 
[Deep Learning Libraries Installer for ArcGIS Pro 3.2](https://links.esri.com/pro-deep-learning-libraries/32)
The installation goes without any problems however inside the Package manager itself there seems to be no sign of Deep Learning Libraries and the number of installed packages stays unchanged as before 390 vs 390

Any advise?
Thanks!

**Comment by cleebp** [comment]
Hi @toralero this is a known visual bug in the backstage package manager ui, the deep-learning-essentials package (and a number of others) won't be listed via the package manger but you can confirm its installed by creating a project, opening a Jupyter notebook, and running `!conda list` to list your full environment's packages, or just `!conda list deep-learning-essentials` if you only want to check that version.

Our base environment we ship with pro only has 250 packages installed so if you are seeing 390 then you definitely have some extra packages from deep-learning. Another thing to make sure of is if you had deep learning installed for a previous Pro version that would need to be uninstalled first.

Let me know if you still run into any issues!

**Comment by toralero** [comment]
Thanks so much! yep this was the case indeed
