### ISSUE TITLE
Unable to Access Offline Installers for Disconnected Environment

### ISSUE THREAD

**Issue by justinhchae** [Esri/deep-learning-frameworks#77]
The instructions at https://github.com/Esri/deep-learning-frameworks/blob/master/README.md?rmedium=links_esri_com_b_d&rsource=https%3A%2F%2Flinks.esri.com%2Fdeep-learning-framework-install#additional-installation-for-disconnected-environment indicate that one can download additional files to support deep learning installation in a disconnected environment. 

However, after signing into the hub community page, I am still unable to access the files. 

![permission denied](https://github.com/Esri/deep-learning-frameworks/assets/68864597/fcbfc1f2-e2a9-4840-8785-91fecbbf9cbe)

Specifically, I would like to download the backbone installer for pro version 2.5-2.8 at https://geosaurus.maps.arcgis.com/home/item.html?id=d404fd50d05d475f8d92eedb78e1c961.

**Comment by scw** [comment]
This issue has been addressed, thanks for the report!
