### ISSUE TITLE
Export Deep Learning Tool , rotation angle parameter

### ISSUE THREAD

**Issue by Boukary** [Esri/deep-learning-frameworks#8]
I m using the Export Deep Learning tool to export image chips from ArcGIS Pro for training purposes. I use the Rotation Angle parameter to generate more augmented images. I use a polygon feature class to delineate the area where image chips will be created, so obviously, some of the rotated images are not created because they are not fully inside the delineated area.

Is it possible to know the rotation angle applied for each image chip?? if yes, how? (the world file associated with each image doesn’t have this info)

**Comment by sang4758** [comment]
We do not write out the rotation angle for each image chip.  Keep in mind when training , the tool also creates random augmented images in memory for training.
