### ISSUE TITLE
Deep learning libraries for ArcGIS Pro 3.3

### ISSUE THREAD

**Issue by Ricardocamachoc** [Esri/deep-learning-frameworks#82]
Hi!
I had to uninstall ArcGIS Pro and deep learning libraries, but now I only have the new 3.3 installer and cannot install the 3.2 deep learning libraries (for obvious reasons...).
I'm wondering when will they be released.
Thanks!

**Comment by cleebp** [comment]
Hi @Ricardocamachoc unfortunately the deep learning installers are not ready for pro 3.3 / enterprise 11.3 yet, these may be delayed another week while the files are being finalized.

If you need deep learning now the easiest solution is to downgrade back to pro 3.2 and install the pro 3.2 deep learning installer until the pro 3.3 installer is released.

You can also follow the [developer steps](https://github.com/Esri/deep-learning-frameworks#developer-install-steps) if you are comfortable using the python command prompt to install the pro 3.3 deep learning files into a clone and use that with pro 3.3 until the installers are released:

1. Open the `Python Command Prompt` window.
    - You can search for this command prompt in the `Start` menu on Windows, or you can launch it from the product's install folder.
    - If running an enterprise product search for the `Python Command Prompt 3`
2. Clone the default Python environment with this command: (don't forget the `--pinned`!)
    > `conda create -n your-clone-name --clone arcgispro-py3 --pinned`
    > e.g: `conda create -n pro33-dl --clone arcgispro-py3 --pinned`
3. When the Python environment has been cloned, activate the cloned environment:
    > `activate your-clone-name`
    - When the cloned enviornment is activated, the new environment name appears at the beginning of the path:
    > `(your-clone-name) C:\Program Files\ArcGIS\Pro\bin\Python\envs>`
4. Install the deep learning essentials libraries into your cloned environment with:
    > `conda install deep-learning-essentials`
    - When prompted to proceed, review the information, type `y`, and press `Enter`
    - If the packages install successfully your cloned enviornment is now setup to run deep learning workflows
5. Type the following command to swap your product's default enviornment to your new cloned environment:
    > `proswap your-clone-name`
    - When you next launch your product it will launch with `your-clone-name` as the active Python Environment and you should now be able to use deep learning tools in Pro 3.3.

**Comment by pjduplooy2022** [comment]
Hi, I have done this procedure, but for some reason when I look at the installed libraries in PRO (in the cloned environment) the version for the deep-learning-essentials lib is still 3.2.

I have the 3.2 package installer uninstalled, as there is no mention of it in the original arcgispro-py3 env.

Is this to be expected?

**Comment by krewdge** [comment]
Hello!

Is there an update on when the Deep learning libraries for ArcGIS Pro 3.3 will be out? Should it be this week or later?

**Comment by rolanddu** [comment]
I really wish I hadn't installed ArcGIS 3.2.  I wish the 3.3 install warned me that that Deep Learning tools weren't ready for 3.3 yet.  My employer (Cylance) blocks me from installing all of the components using the clone environment approach. I look forward to the 3.3 install files to become available.  Please let me know how I might help with testing or contributing to the 3.3 install for Windows.  I don't see the development here on GitHub.

**Comment by scw** [comment]
Installers for Pro 3.3 will be made available this week and are currently going through their internal QA before we post them. Thanks!

**Comment by ingallandy** [comment]
Any news on the installers for Pro 3.3, the week of the 27th May is almost over...lol

**Comment by scw** [comment]
@ingallandy Pro 3.3 setups are now live. Let us know if you run into anything!
