### ISSUE TITLE
Deep Learning libraries for ArcGIS Pro 2.7

### ISSUE THREAD

**Issue by kv5784** [Esri/deep-learning-frameworks#9]
Hello,

We are trying to test Deep Learning function on ArcGIS Pro 2.7 by installing all the required libraries as provided in this document: http://downloads.esri.com/resources/ImageAnalyst/DeepLearning_FAQ.pdf
![ArcGISPro27_LibLists](https://user-images.githubusercontent.com/74392730/102862029-15048180-4463-11eb-9df4-c3f95a2e4d00.jpg)
However, in the installing process, many others libraries on the lists are required to be downgraded and upgraded to a compatible version with the installing version libraries. For instance, when installing ‘cudatoolkit=10.1.243,’ ArcGIS Pro is asked to be downgraded to version 2.3 as shown in the picture below:
![DowngradedPro_Highlighted](https://user-images.githubusercontent.com/74392730/102862055-20f04380-4463-11eb-8b12-df64e9977f0f.jpg)

We are concerned that when all the libraries are installed, the version of each libraries will conflict with each other. As mentioned in ArcGIS Pro version case, all theses libraries are for ArcGIS Pro 2.7 but why ArcGIS Pro is required to be downgraded to an earlier version?

Please help advice on this issue.

Thanks in advanced!
Kulanit

**Comment by cleebp** [comment]
@kv5784 currently the deep learning installer/package set for ArcGIS Pro 2.7 is still under development, the installers should be available by mid-January - I will update/close this issue when they are available for public use.

You should not downgrade your `arcgispro` package to `2.3`, I would not expect the resulting environment to work with pro 2.7.

In the meantime you can use the following command line steps to install the package set for deep-learning in pro 2.7:
- First clone your default `arcgispro-py3` environment from the ArcGIS Pro python backstage
- Open the `python command prompt`
- Activate your clone if the command prompt launched with `arcgispro-py3` active (make sure to `cd ..` if you are still in `arcgispro-py3`'s directory)
- Run `conda install deep-learning-essentials=2.7`
  - This command should pull in most of the corresponding packages on [this document](http://downloads.esri.com/resources/ImageAnalyst/DeepLearning_FAQ.pdf)

_Note: this package set is still under development so if you run into any issues please report them here._ 

Hope this helps! 😸

**Comment by xabierr** [comment]
Hi Brian, Im getting a "packages are not available from current channels" error message when trying this.

**Comment by xabierr** [comment]
worked just running 

conda install deep-learning-essentials

**Comment by kv5784** [comment]
@cleebp 
Thank you for your help!

**Comment by sldeitz** [comment]
@cleebp I just updated to Pro 2.7 and downloaded the deep learning libraries through the file - thank you! The only problem is that when I try to open a Jupyter notebook the program crashes. Any ideas as to why? This occurs when I try to open a previous notebook and when I try to add a new one (I think it might have to do with initializing the kernel?).
