### ISSUE TITLE
Cannot train UNet model with default parameters in ArcGIS Pro 3.2.2

### ISSUE THREAD

**Issue by hellwue** [Esri/deep-learning-frameworks#90]
ArcGIS Pro Version: 3.2.2.
deep-learning-essentials installed like described here under "Developer install steps".

When trying to train a UNet model through the "Train Deep Learning Model" tool it results in an error. 

![Screenshot 2024-06-20 134743](https://github.com/Esri/deep-learning-frameworks/assets/95623944/48ddab27-27cc-4759-8793-a796fca8f1e1)

The stack trace when doing this in a Notebook reveals that this issue stems from `fastai` when it checks if there are pretrained models in  `torchvision.models`, as there are none with the suffix "_weights" as shown in the screenshot below:

![Screenshot 2024-06-20 135011](https://github.com/Esri/deep-learning-frameworks/assets/95623944/2583a61a-c18c-4a9f-a178-87716a561539)

This weight suffix only seems available for torchvision>=0.13, but version 0.9.2 is installed... 

This error still occurs when installing the arcgis deep learning backbones for disconnected environments.

**Comment by scw** [comment]
@hellwue What version of the Python API are you using? It could be a mismatch there if the environment has been upgraded with a newer API release, but I would only expect that to be the case in a custom environment (not the default `arcgispro-py3` with DL installer overlaid)

**Comment by scw** [comment]
@hellwue Haven't heard back so closing this, but if you continue to have issues with the package versions let us know the details and we can take a look.
